// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftpmfnigubshfarshebm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cG1mbmlndWJzaGZhcnNoZWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQ1MjgsImV4cCI6MjA2NTU2MDUyOH0._YQgeTMBUXEfz80EDD8YPjveQJ2U4LlfRVH2xjuqpX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);